// GENERATED by scripts/ui-atlas.mjs — do not edit.
//
// DOM-free on purpose: tests/icons.test.ts imports this under Vitest's node
// environment to check that every currency and district has a cell.

export const ATLAS_CELL = 32;
export const ATLAS_COLS = 16;

export const ICON_INDEX = {
  'Berries': 0,
  'Berries-locked': 1,
  'Fish': 2,
  'Fish-locked': 3,
  'Food': 4,
  'Food-locked': 5,
  'Food-sm': 6,
  'Gems': 7,
  'Gems-locked': 8,
  'Gems-sm': 9,
  'Gold': 10,
  'Gold-locked': 11,
  'Gold-sm': 12,
  'Iron': 13,
  'Iron-locked': 14,
  'Iron-sm': 15,
  'Knowledge': 16,
  'Knowledge-locked': 17,
  'Knowledge-sm': 18,
  'Stone': 19,
  'Stone-locked': 20,
  'Stone-sm': 21,
  'Wood': 22,
  'Wood-locked': 23,
  'Wood-sm': 24,
  'builders': 25,
  'builders-locked': 26,
  'population': 27,
  'population-locked': 28,
  'workers': 29,
  'workers-locked': 30,
} as const;

/** Cells the atlas actually provides. An icon absent from this set falls back
 *  to its emoji, so art can land one sheet at a time. */
export const ATLAS_CELLS: ReadonlySet<string> = new Set(Object.keys(ICON_INDEX));
